# Generated by Django 3.2.4 on 2021-06-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.AddField(
            model_name='postac',
            name='rola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='League.rola'),
        ),
    ]
