# Generated by Django 3.2.4 on 2021-06-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0002_auto_20210624_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pozycja',
                'verbose_name_plural': 'Pozycje',
            },
        ),
        migrations.AddField(
            model_name='postac',
            name='pozycja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='League.pozycja'),
        ),
    ]
