# Generated by Django 3.2.4 on 2021-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=2000)),
                ('kod', models.CharField(max_length=10)),
                ('nazwaP', models.CharField(max_length=100)),
                ('opisP', models.CharField(max_length=500)),
                ('nazwaQ', models.CharField(max_length=100)),
                ('opisQ', models.CharField(max_length=500)),
                ('nazwaW', models.CharField(max_length=100)),
                ('opisW', models.CharField(max_length=500)),
                ('nazwaE', models.CharField(max_length=100)),
                ('opisE', models.CharField(max_length=500)),
                ('nazwaR', models.CharField(max_length=100)),
                ('opisR', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Postać',
                'verbose_name_plural': 'Postacie',
            },
        ),
    ]
